version: '3.7'

services:
    backend:
        env_file: .env
        build: 
            context: hepsiburadaSociality
            dockerfile: ./Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        ports: 
            - 8000:8000
    frontend:
        build:
            context: hepsi_frontend
            dockerfile: ./Dockerfile
        ports:
        - '8081:8080'
        depends_on:
            - "backend"